default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5433

development:
  <<: *default
  database: winnipeg_home_essentials_development
  username: shelly
  password: password

test:
  <<: *default
  database: winnipeg_home_essentials_test
  username: shelly
  password: password

production:
  <<: *default
  database: winnipeg_home_essentials_production
  username: winnipeg_home_essentials
  password: <%= ENV["WINNIPEG_HOME_ESSENTIALS_DATABASE_PASSWORD"] %>
